CREATE OR REPLACE FUNCTION getCodeNm(
	P_CODE_TYPE VARCHAR(30), 
	P_CODE VARCHAR(30) 
) RETURNS VARCHAR(30)
BEGIN
	
    DECLARE RETURN_STR VARCHAR(50);
	
    SELECT CODE_NM INTO RETURN_STR 
    FROM (
	    SELECT 
	    		CODE_NM , 
	    		ROW_NUMBER() OVER (PARTITION BY CODE ORDER BY CODE DESC) AS ROW_NUM 
	    FROM    CODE_MASTER CM 
	    WHERE   CODE_TYPE =P_CODE_TYPE 
	    AND 	CODE=P_CODE
    )A  
    WHERE ROW_NUM=1;
  
	RETURN RETURN_STR;
		
END;