CREATE OR REPLACE PROCEDURE USER_PROFILE_SET(
	P_USER_ID	      VARCHAR(30),
	P_USER_NICKNAME   VARCHAR(100),
	P_USER_GENDER	  VARCHAR(10),
	P_USER_BIRTHDATE  DATE,
	P_USER_DRINK	  VARCHAR(2),
	P_USER_SMOKING    VARCHAR(2),
	P_USER_BLOOD	  VARCHAR(10),
	P_USER_INTRO	  VARCHAR(10),
	P_I_ARR			  varchar(3000),
	P_L_ARR	          varchar(3000),
	P_P_ARR	          varchar(3000),
	P_pkg             varchar(30)
)
BEGIN

	
-- 	유저 테이블 수정
	UPDATE USER_ATTR SET 
		   USER_NICKNAME=P_USER_NICKNAME, 
		   USER_GENDER=P_USER_GENDER, 
		   USER_BIRTHDATE = DATE_FORMAT( P_USER_BIRTHDATE ,'%Y-%m-%d'),
		   USER_DRINK = P_USER_DRINK,
		   USER_SMOKING = P_USER_SMOKING,
		   USER_BLOOD = P_USER_BLOOD,
		   USER_INTRO = P_USER_INTRO,
		   UPDATE_DATE = NOW(),
		   UPDATE_BY = P_USER_ID
	WHERE  USER_ID=P_USER_ID;

-- 	관심 추가
	DELETE FROM USER_INTEREST WHERE USER_ID=P_USER_ID;
	FOR i IN 1..(COUNT_STR( P_I_ARR , P_pkg )+1)
	DO
		INSERT INTO USER_INTEREST(USER_ID, I_TYPE, CREATE_DATE) VALUES(P_USER_ID,  GET_ARRSTR(P_I_ARR , P_pkg , i), now() );
	END FOR;
	
-- 	위치 추가
	DELETE FROM USER_LOCATION WHERE USER_ID=P_USER_ID;
	FOR i IN 1..(COUNT_STR( P_L_ARR , P_pkg )+1)
	DO
		INSERT INTO USER_LOCATION (USER_ID, LOC_API_ID, ORDR_NO) VALUES(P_USER_ID, GET_ARRSTR(P_L_ARR , P_pkg , i), i );
	END FOR;

--  성격 추가
	DELETE FROM USER_PERSONALITY WHERE USER_ID=P_USER_ID;
	FOR i IN 1..(COUNT_STR( P_P_ARR , P_pkg )+1)
	DO
		INSERT INTO USER_PERSONALITY (USER_ID, P_TYPE, CREATE_DATE) VALUES(P_USER_ID, GET_ARRSTR(P_P_ARR , P_pkg , i), now()  );
	END FOR;
	
	COMMIT;



END