CREATE TABLE CODE_MASTER ( 
    CODE_ID VARCHAR(50) NOT NULL,
    CODE_TYPE VARCHAR(30) NOT NULL,
    CODE VARCHAR(30) NOT NULL,
    CODE_NM VARCHAR(50) NOT NULL,
    USE_YN VARCHAR(2) NOT NULL,
    CREATE_DATE DATETIME,
    UPDATE_DATE DATETIME,
    ORDR_NO INT 
);

-- INDEX
CREATE INDEX CODES_INDEX1 ON CODE_MASTER (CODE_TYPE);
-- 기본키 생성
ALTER TABLE CODE_MASTER ADD CONSTRAINT CODE_ID_PK PRIMARY KEY (CODE_ID);
-- 테이블 자동 증가(AUTO INCREMENT) 생성
ALTER TABLE CODE_MASTER MODIFY COLUMN CODE_ID BIGINT NOT NULL AUTO_INCREMENT;
-- 테이블 자동 증가(Auto Increment)에 대한 시작 값
ALTER TABLE CODE_MASTER AUTO_INCREMENT = 1;