CREATE TABLE ERR_LOG ( 
	LOG_ID VARCHAR(30) NOT NULL,
	CREATE_DATE DATETIME NULL,
	CREATE_BY   DATETIME NULL,
	LOG_CONTENT VARCHAR(3000) NULL 
);


-- 사용자 테이블 기본키 생성
ALTER TABLE ERR_LOG ADD CONSTRAINT ERR_LOG_ID PRIMARY KEY (LOG_ID);
-- 테이블 자동 증가(AUTO INCREMENT) 생성
ALTER TABLE ERR_LOG MODIFY COLUMN LOG_ID BIGINT NOT NULL AUTO_INCREMENT;
-- 테이블 자동 증가(Auto Increment)에 대한 시작 값
ALTER TABLE ERR_LOG AUTO_INCREMENT = 1;