
CREATE TABLE FILE_MASTER ( 
	FILE_ID VARCHAR(30) NOT NULL,
	REF_ID VARCHAR(30) NOT NULL,
	FILE_NAME VARCHAR(50) ,
	FILE_PATH VARCHAR(100) ,
	CREATE_DATE DATETIME ,
	DELETE_YN VARCHAR(2) ,
	ORDR_NO INT  ,
	file_type varchar(100) DEFAULT NULL COMMENT '파일타입(게시판,프로필)',
);

-- INDEX
CREATE INDEX FILES_INDEX1 ON FILE_MASTER (REF_ID);
CREATE INDEX FILES_INDEX1 ON FILE_MASTER (file_type);
-- 기본키 생성
ALTER TABLE FILE_MASTER ADD CONSTRAINT CODE_ID_PK PRIMARY KEY (FILE_ID);
-- 테이블 자동 증가(AUTO INCREMENT) 생성
ALTER TABLE FILE_MASTER MODIFY COLUMN FILE_ID BIGINT NOT NULL AUTO_INCREMENT;
-- 테이블 자동 증가(Auto Increment)에 대한 시작 값
ALTER TABLE FILE_MASTER AUTO_INCREMENT = 1;

