CREATE TABLE LOGIN_LOG (
	LOG_ID       INT,
	USER_ID	     VARCHAR(30),
	CREATE_DATE	 DATETIME,
	LOG_TYPE	 VARCHAR(10)
);

-- 기본키 생성
ALTER TABLE LOGIN_LOG ADD CONSTRAINT LOG_ID_PK PRIMARY KEY (LOG_ID);
-- 테이블 자동 증가(AUTO INCREMENT) 생성
ALTER TABLE LOGIN_LOG MODIFY COLUMN LOG_ID BIGINT NOT NULL AUTO_INCREMENT;
-- 테이블 자동 증가(Auto Increment)에 대한 시작 값
ALTER TABLE LOGIN_LOG AUTO_INCREMENT = 1;