CREATE TABLE USER_PERSONALITY (
	P_ID	    VARCHAR(100)	NOT NULL,
	USER_ID	    VARCHAR(30)	    NOT NULL,
	P_TYPE	    VARCHAR(100)	NULL,
	CREATE_DATE	DATETIME	NULL
);

-- 사용자 테이블 기본키 생성
ALTER TABLE USER_PERSONALITY ADD CONSTRAINT PERSONALITY_ID PRIMARY KEY (P_ID);
-- INDEX
CREATE INDEX P_INDEX1 ON USER_PERSONALITY (USER_ID);
-- 테이블 자동 증가(AUTO INCREMENT) 생성
ALTER TABLE USER_PERSONALITY MODIFY COLUMN P_ID BIGINT NOT NULL AUTO_INCREMENT;
-- 테이블 자동 증가(Auto Increment)에 대한 시작 값
ALTER TABLE USER_PERSONALITY AUTO_INCREMENT = 1;