CREATE TABLE USER_INTEREST (
	I_ID	    VARCHAR(100)	NOT NULL,
	USER_ID	    VARCHAR(30)	    NOT NULL,
	I_TYPE	    VARCHAR(100)	NULL,
	CREATE_DATE	DATETIME	        NULL
);

-- 사용자 테이블 기본키 생성
ALTER TABLE USER_INTEREST ADD CONSTRAINT INTEREST_ID PRIMARY KEY (I_ID);
-- INDEX
CREATE INDEX I_INDEX1 ON USER_INTEREST (USER_ID);
-- 테이블 자동 증가(AUTO INCREMENT) 생성
ALTER TABLE USER_INTEREST MODIFY COLUMN I_ID BIGINT NOT NULL AUTO_INCREMENT;
-- 테이블 자동 증가(Auto Increment)에 대한 시작 값
ALTER TABLE USER_INTEREST AUTO_INCREMENT = 1;