CREATE TABLE USER_LOCATION (
	LOC_ID	    VARCHAR(30)	NOT NULL,
	USER_ID	    VARCHAR(30)	NOT NULL,
	LOC_API_ID	VARCHAR(30)	NULL,
	ORDR_NO	    INTEGER	    NULL
);

-- 사용자 테이블 기본키 생성
ALTER TABLE USER_LOCATION ADD CONSTRAINT LOC_ID PRIMARY KEY (LOC_ID);
-- INDEX
CREATE INDEX L_INDEX1 ON USER_LOCATION (USER_ID);
-- 테이블 자동 증가(AUTO INCREMENT) 생성
ALTER TABLE USER_LOCATION MODIFY COLUMN LOC_ID BIGINT NOT NULL AUTO_INCREMENT;
-- 테이블 자동 증가(Auto Increment)에 대한 시작 값
ALTER TABLE USER_LOCATION AUTO_INCREMENT = 1;