
CREATE TABLE USER_ATTR (
	USER_ID	VARCHAR(30)	NOT NULL,
	USER_NICKNAME	VARCHAR(100)	NULL,
	USER_GENDER	VARCHAR(10)	NULL,
	USER_BIRTHDATE	DATE	NULL,
	USER_DRINK	VARCHAR(2)	NULL,
	USER_SMOKING	VARCHAR(2)	NULL,
	USER_BLOOD	VARCHAR(10)	NULL,
	CREATE_DATE	DATETIME	NULL,
	UPDATE_DATE	DATETIME	NULL,
	CREATE_BY	VARCHAR(30)	NULL,
	UPDATE_BY	VARCHAR(30)	NULL,
	LOG_YN	VARCHAR(30)	NULL,
	SHOW_YN	VARCHAR(30)	NULL,
	AD_AGREE	VARCHAR(5)	NULL,
	USER_INTRO LONGBLOB default null
);

-- 사용자 속성 테이블 기본키 생성
ALTER TABLE USER_ATTR ADD CONSTRAINT USER_ATTR_PK PRIMARY KEY (USER_ID);
-- INDEX
CREATE INDEX USER_ARRT_INDEX1 ON USER_ATTR (USER_ID);
-- 초기 데이터
INSERT INTO USER_ATTR(USER_ID , CREATE_DATE,CREATE_BY)
VALUES ('admin',now(),'init');